### ISSUE TITLE
Helicopters disappearing from store over time

### ISSUE THREAD

**Issue by RichardPilbery** [RichardPilbery/DAA_DES#139]
Since the earlier commits, it now appears that helicopters are being removed from the store, resulting in only cars being available. Started within the last couple of commits.

**Comment by Bergam0t** [comment]
Aha! Yes, that matches with what I'm seeing when testing the fix for #136

![Image](https://github.com/user-attachments/assets/50b03912-3b04-4bb7-b876-261bd7bc7e33)

**Comment by RichardPilbery** [comment]
Should be fixed now. However, still more car cases than helicopters vs historic data for some reason.

**Comment by Bergam0t** [comment]
So it looks like H70 is now behaving as expected but H71 not returning to action after its first service

![Image](https://github.com/user-attachments/assets/16a0b0bd-64ca-4bc1-8e13-c9252fe41e7c)

**Comment by Bergam0t** [comment]
Resources now appear to be correctly returning to store after servicing

![Image](https://github.com/user-attachments/assets/12e589a0-308d-4897-8b8b-b3e5fe302cb8)

(possibly some other minor issues remaining around service dates - will open separate issue for that)
